#!/usr/bin/env python3
"""Regenerate third-party notices from locked Cargo sources; --check detects drift."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "THIRD_PARTY_NOTICES.md"
NOTICE = re.compile(r"(?i)^(licen[cs]es?|copying|copyright|notices?|unlicense|authors)([._-]|$)")


def selected_license(expression):
    # Only simple OR choices and the Unicode conjunctions observed in Cargo.lock.
    # Fail on unfamiliar expressions instead of silently accepting new obligations.
    conjunctions = {
        "(MIT OR Apache-2.0) AND Unicode-3.0": "MIT AND Unicode-3.0",
        "(MIT OR Apache-2.0) AND Unicode-DFS-2016": "MIT AND Unicode-DFS-2016",
        "MIT AND Unicode-DFS-2016": "MIT AND Unicode-DFS-2016",
    }
    if expression in conjunctions:
        return conjunctions[expression]
    alternatives = [s.strip() for s in expression.replace("/", " OR ").split(" OR ")]
    for license in ("MIT", "Apache-2.0", "0BSD", "Zlib", "BSL-1.0", "Unlicense", "WTFPL"):
        if license in alternatives:
            return license
    raise ValueError(f"Review unsupported license expression: {expression!r}")


def generate():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1"], cwd=ROOT))
    supplements = {s["package"]: s for s in json.loads(
        (ROOT / "licenses/supplemental.json").read_text())}
    packages = sorted((p for p in metadata["packages"] if p["id"] not in metadata["workspace_members"]),
                      key=lambda p: (p["name"], p["version"]))
    texts = {}
    rows = []
    for package in packages:
        name, version = package["name"], package["version"]
        key = f"{name}@{version}"
        license = package["license"] or "UNDECLARED"
        selected = selected_license(license)
        root = Path(package["manifest_path"]).parent
        documents = []
        for path in sorted(root.rglob("*")):
            if not path.is_file() or not NOTICE.match(path.name):
                continue
            if name == "termina" and path.name == "LICENSE-MPL":
                continue  # We select the independently offered MIT license.
            source = f"https://docs.rs/crate/{name}/{version}/source/{quote(path.relative_to(root).as_posix())}"
            documents.append({"source": source, "text": path.read_text(encoding="utf-8")})
        supplement = supplements.pop(key, {})
        for filename, expected in supplement.get("asset_sha256", {}).items():
            actual = hashlib.sha256((root / "assets" / filename).read_bytes()).hexdigest()
            if actual != expected:
                raise ValueError(f"Re-audit bundled asset: {key}/{filename}")
        documents.extend(supplement.get("documents", []))
        if not documents or not any(d["text"].strip() for d in documents):
            raise ValueError(f"Missing license text: {key}")
        references = []
        for document in documents:
            text = "\n".join(line.rstrip() for line in document["text"].splitlines()).strip()
            if not text:
                continue
            if text not in texts:
                texts[text] = (len(texts) + 1, [])
            number, sources = texts[text]
            source = f"[{key}]({document['source']})"
            if source not in sources:
                sources.append(source)
            reference = f"[{number}](#notice-{number})"
            if reference not in references:
                references.append(reference)
        rows.append(f"| {name} | {version} | {license} | {selected} | {', '.join(references)} |")
    if supplements:
        raise ValueError(f"Re-audit supplements after dependency changes: {', '.join(supplements)}")
    sections = [
        "# Third-party notices\n\n"
        "annodiff itself is MIT licensed; dependencies retain their own licenses.\n\n"
        "Generated by `python3 licenses/generate.py` from `Cargo.lock`, crate license files, "
        "and the reviewed upstream material in `licenses/supplemental.json`. "
        "Includes optional, build, and target-specific dependencies; not all are linked into every binary.\n\n"
        "The selected license column records our choice where alternatives are offered. "
        "Upstream texts may mention other available licenses; preserving those texts does not select them. "
        "Additional Unicode terms and bundled-asset notices are retained.\n\n"
        "Include this file and `LICENSE` with binary distributions. "
        "Both are also embedded in the executable and available through `annodiff --licenses`.\n\n"
        "## Dependencies\n\n"
        "| Crate | Version | Declared license | Selected license | Notices |\n"
        "|---|---|---|---|---|\n" + "\n".join(rows),
        "## License texts and attributions",
    ]
    for text, (number, sources) in texts.items():
        sections.append(f"### Notice {number}\n\n" + " · ".join(sources)
                        + "\n\n````text\n" + text + "\n````")
    return "\n\n".join(sections) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if notices need regeneration")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != result:
            parser.exit(1, "Third-party notices are stale; run python3 licenses/generate.py\n")
        print("Third-party notices are up to date.")
    else:
        OUTPUT.write_text(result, encoding="utf-8")
        print(f"Wrote {OUTPUT.name} ({len(result.encode())} bytes).")
